### ISSUE TITLE
add clj-kondo config export

### ISSUE THREAD

**Issue by flyingmachine** [lambdaisland/ornament#16]
it would be super dope to get clj-kondo to recognize `o/defstyled` :)

**Comment by plexus** [comment]
I'm not a clj-kondo  user. What would this entail exactly?

**Comment by jeans11** [comment]
For a quick fix, people can add in their `clj-kondo` `config.edn` this entry: `lambdaisland.ornament/defstyled clojure.core/def` (in `:lint-as`)
