### ISSUE TITLE
Do we still want to support tailwind v2, or move everything over to tailwind v3?

### ISSUE THREAD

**Issue by oxalorg** [lambdaisland/ornament#18]
Girouette v0.0.8 introduced support for TW v3.

Along with it, they made some [breaking changes](https://github.com/green-coder/girouette/blob/master/CHANGELOG.md#breaking-changes) such that we can still continue supporting TW v2 if we would like.

Tailwind v3 bring a lot of welcome upgrades and doesn't have many [breaking changes](https://tailwindcss.com/docs/upgrade-guide) from v2

**Comment by GetBitOutdoors** [comment]
I cannot get this fork working.
When I try to render a `defstyled` component with garden syntax it works.
But if I add a girouette token it fails with error
`Execution error (NullPointerException) at lambdaisland.ornament/class-name->garden (ornament.cljc:129).
Cannot invoke "clojure.lang.IFn.invoke(Object)"`

What are the current best practices for using Tailwind 3 tokens?
