### ISSUE TITLE
Overload style rules on a styled component with custom render fn?

### ISSUE THREAD

**Issue by GetBitOutdoors** [lambdaisland/ornament#21]
How can I pass and update a styled component with a render body
```
(defstyled component 
  :div :font-bold 
  ([] 
   [:<> [:span "hello"]]))

(defstyled component2 component 
  :text-red-500)

[component2]
```
Should return the composition of the perent component, but also the rendered body of the parent? Or is there another patern for this?

On thing this pattern would allow is to inherit the behavior of a styled cumponent with a custom render fn, and override it's styling with garden/girouette/tailwind keyword-based css-token syntax. 
I know I can now pass html attrs to a custom-render component. But I don't think that solves this case...

**Comment by GetBitOutdoors** [comment]
Maybe being able to pass a render function to a `defstyled` component would help this case. I could not seem to do that.

**Comment by plexus** [comment]
Inheritence of function tails wasn't implemented yet, I've added it in `0.8.84`

**Comment by plexus** [comment]
That's a very abstract question which I'm having difficulty parsing. Maybe you can give some examples of what you're trying to do?

Ornament only provides mechanisms, we don't really dictate what the right way is to use it, but I'm happy to try to give you some suggestions if you show me what you're trying to do.

You might also want to look into setting custom tokens on the girouette level, see the README for info on that.

**Comment by GetBitOutdoors** [comment]
I guess I was describing the code example in the first comment. That is not supported right? What is the best approach for this? (using the default Girouette tokens)

**Comment by plexus** [comment]
It's supported since 0.8.84.
