### ISSUE TITLE
Garden vector of selectors missing extra

### ISSUE THREAD

**Issue by JohanCodinha** [lambdaisland/ornament#3]
`(o/defstyled Test :div
  {:color :red}
  [:p :span {:color :blue}])`
expand to this css string => .ns__Test{color:red}.ns__Test p{color:blue}
expected is => .ns__Test{color:red}.ns__Test p span{color:blue}

Here's the Garden rule [doc](https://github.com/noprompt/garden/wiki/Syntax#rules)

**Comment by JohanCodinha** [comment]
Thanks.
Just to clarify [:p :span {:color :blue}] is supposed to target both :p and :span and not a :span nestead in a :p

**Comment by plexus** [comment]
Thanks for clarifying, that does make me think we should address this.

**Comment by plexus** [comment]
For "or" selectors we have for some time supported sets.

```clj
[#{:p :span} {:color "blue"}]
```
